### ISSUE TITLE
When using (forked) TypeORM I get the followin errors ...

### ISSUE THREAD

**Issue by acrodrig** [denolib/typeorm#141]
**Issue type:**

[ ] question
[X] bug report
[ ] feature request
[ ] documentation issue

**TypeORM version:**

[X] `latest`
[ ] `@next`
[ ] `0.x.x` (or put your version here)

**Deno version:**

`1.9`

**Steps to reproduce or a small repository showing the problem:**

```
error: TS2612 [ERROR]: Property 'manager' will overwrite the base property in 'Repository<Entity>'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    readonly manager!: MongoEntityManager;
             ~~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/repository/MongoRepository.ts:51:14

TS2612 [ERROR]: Property 'databaseConnection' will overwrite the base property in 'BaseQueryRunner'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    protected databaseConnection!: PoolClient;
              ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/driver/postgres/PostgresQueryRunner.ts:57:15

TS2612 [ERROR]: Property 'databaseConnection' will overwrite the base property in 'BaseQueryRunner'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    protected databaseConnection!: [Connection, () => Promise<void>];
              ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/driver/mysql/MysqlQueryRunner.ts:54:15

TS2612 [ERROR]: Property 'options' will overwrite the base property in 'AbstractSqliteDriver'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    options!: SqljsConnectionOptions;
    ~~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/driver/sqljs/SqljsDriver.ts:23:5

TS2612 [ERROR]: Property 'databaseConnection' will overwrite the base property in 'AbstractSqliteDriver'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    databaseConnection!: DB;
    ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/driver/sqlite/SqliteDriver.ts:29:5

TS2612 [ERROR]: Property 'sqlite' will overwrite the base property in 'AbstractSqliteDriver'. If this is intentional, add an initializer. Otherwise, add a 'declare' modifier or remove the redundant declaration.
    sqlite!: DenoSqlite;
    ~~~~~~
    at https://deno.land/x/typeorm@v0.2.23-rc10/src/driver/sqlite/SqliteDriver.ts:31:5

Found 6 errors.
```

**Comment by Dev-Addict** [comment]
same here.
I think there is a big problem with deno orms non of them are working expect for mongo and I'm trying to use mysql.
if anyone knows the solution or a workaround please help this problem still exists
